[package]
name = "pop"
version = "0.1.0"
authors = ["nikori"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12"
sysfs_gpio = "0.5"
spidev = "0.4"
